# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ferzim/conversao-temperatura-semanak8s:v1
          ports:
            - containerPort: 8081
---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001
#  type: NodePort para testar local
  type: LoadBalancer